messages = [
    "You are capable of amazing things.",
    "Believe in yourself.",
    "Every day is a fresh start.",
    "You are stronger than you think.",
    "Keep going, you're doing great!",
    "Your potential is limitless.",
    "Stay positive, work hard, make it happen.",
    "Be proud of how far you've come.",
    "You are enough.",
    "You make a difference.",
    "Good things take time.",
    "Dream big and dare to fail.",
    "You’ve got this!",
    "Positivity always wins.",
    "Don't stop until you're proud.",
    "Keep shining.",
    "You are worthy of success.",
    "Kindness is your superpower.",
    "Mistakes are proof that you're trying.",
    "You can handle this.",
    "You are doing better than you think.",
    "Focus on the good.",
    "Believe in your dreams.",
    "Stay strong and never give up.",
    "One step at a time.",
    "Your mindset determines your success.",
    "You are unstoppable.",
    "Trust the process.",
    "Choose happiness.",
    "Progress, not perfection.",
    "You are resilient.",
    "Keep believing in yourself.",
    "Radiate positivity.",
    "Small steps lead to big results.",
    "You are a work of art.",
    "Stay hopeful.",
    "You are not alone.",
    "Push yourself, because no one else will do it for you.",
    "Your future is bright.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "You inspire others.",
    "Turn challenges into opportunities.",
    "Success starts with self-belief.",
    "You are capable of greatness.",
    "Live with purpose.",
    "You have what it takes.",
    "Shine bright, no matter what.",
    "Be your best self.",
    "You are creating a better future."
]

br_messages = [
    "Você é capaz de coisas incríveis.",
    "Acredite em si mesmo.",
    "Todo dia é um novo começo.",
    "Você é mais forte do que pensa.",
    "Continue, você está indo muito bem!",
    "Seu potencial é ilimitado.",
    "Mantenha-se positivo, trabalhe duro e faça acontecer.",
    "Tenha orgulho de até onde você chegou.",
    "Você é suficiente.",
    "Você faz a diferença.",
    "Coisas boas levam tempo.",
    "Sonhe grande e ouse falhar.",
    "Você consegue!",
    "A positividade sempre vence.",
    "Não pare até se orgulhar.",
    "Continue brilhando.",
    "Você é digno do sucesso.",
    "A gentileza é o seu superpoder.",
    "Erros são provas de que você está tentando.",
    "Você consegue lidar com isso.",
    "Você está indo melhor do que imagina.",
    "Concentre-se no que é bom.",
    "Acredite nos seus sonhos.",
    "Seja forte e nunca desista.",
    "Um passo de cada vez.",
    "Sua mentalidade determina seu sucesso.",
    "Você é imparável.",
    "Confie no processo.",
    "Escolha ser feliz.",
    "Progresso, não perfeição.",
    "Você é resiliente.",
    "Continue acreditando em si mesmo.",
    "Irradie positividade.",
    "Pequenos passos levam a grandes resultados.",
    "Você é uma obra de arte.",
    "Mantenha a esperança.",
    "Você não está sozinho.",
    "Desafie-se, pois ninguém fará isso por você.",
    "Seu futuro é brilhante.",
    "Seja destemido na busca do que faz sua alma vibrar.",
    "Você inspira outras pessoas.",
    "Transforme desafios em oportunidades.",
    "O sucesso começa com acreditar em si mesmo.",
    "Você é capaz de grandes feitos.",
    "Viva com propósito.",
    "Você tem o que é preciso.",
    "Brilhe intensamente, não importa o que aconteça.",
    "Seja sua melhor versão.",
    "Você está criando um futuro melhor."
]